### ISSUE TITLE
E. Gadd Gameboy Horror Softlock

### ISSUE THREAD

**Issue by orangeisborange** [Medacorp/Luigi-s-Mansion#59]
**Describe the bug**
When E. Gadd messages you via Gameboy Horror, if you scroll too fast and close out the prompt, the screen will turn green leaving you soft locked.

**To Reproduce**
Wait for E. Gadd to call, answer and then scroll to the left or right immediataely.

**Expected behavior**
E. Gadd should explain whatever he needs to explain, and then hang up.

**Attachments**
![image](https://user-images.githubusercontent.com/66503790/165293214-4a3cca6b-ea90-4ee6-9f60-70028f9bc573.png)

**Map version:**
1.18.2 Minecraft
1.5v map

**Additional context**

Additional controller mod "Controllable", but this only affects inputs by putting them on a gamepad. Should not cause these sorts of things.

**Comment by Dhranios** [comment]
This isn't a sodtlock, but an intentional mechanic of the map so you can skip the calls; your movement will get unlocked again when you or E. Gadd hangs up.
If E. Gadd was supposed to teleport you back to the lab, the message from the gameboy horror will ask for you go back. (The gameboy horror message is actually a summary of the dialog that would've taken place.)

**Comment by Dhranios** [comment]
Oh, now I found the softlock, it's an animation issue.

**Comment by orangeisborange** [comment]
> Oh, now I found the softlock, it's an animation issue. This can be fixed with a simple relog. This is the only GBH call that's affected.

Thanks, I'll relog and continue my playthrough soon!
